//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Conjugation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Conjugation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Conjugation", typeof(Conjugation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;plainForm&quot;: &quot;見る&quot;,
        ///    &quot;type&quot;: &quot;Ichidan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;歌う&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;立つ&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;怒る&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;読む&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;死ぬ&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;遊ぶ&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;続く&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  {
        ///    &quot;plainForm&quot;: &quot;泳ぐ&quot;,
        ///    &quot;type&quot;: &quot;Godan&quot;
        ///  },
        ///  { [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Verbs {
            get {
                return ResourceManager.GetString("Verbs", resourceCulture);
            }
        }
    }
}
